import { Routes } from "@angular/router";
import { CompanyComponent } from "./company.component";
import { DashboardComponent } from "./pages/dashboard/dashboard.component";
import { AppointmentComponent } from "./pages/appointment/appointment.component";
import { MedicalRecordComponent } from "./pages/medical-record/medical-record.component";
import { EventsArticleComponent } from "./pages/events-article/events-article.component";
import { EmployeeRegistrationComponent } from "./pages/employee-registration/employee-registration.component";
import { FeedbackComponent } from "./pages/feedback/feedback.component";
import { EmployeeTrackingComponent } from "./pages/employee-tracking/employee-tracking.component";
import { HealthAnalysisComponent } from "./pages/health-analysis/health-analysis.component";
import { HealthStatusComponent } from "./pages/health-status/health-status.component";
import { BookedAppointmentComponent } from "./pages/booked-appointment/booked-appointment.component";
import { EmployeesTempComponent } from "./pages/employees-temp/employees-temp.component";
import { MaintainanceComponent } from './maintainance/maintainance.component';

export const CompanyRoutes: Routes = [
  { path: "", component: DashboardComponent },
  { path: "event-article", component: MaintainanceComponent },
  { path: "appointment", component: MaintainanceComponent },
  { path: "booked-appointment", component: MaintainanceComponent },
  { path: "health-status", component: MaintainanceComponent },
  { path: "employment-report", component: MaintainanceComponent },
  { path: "registration", component: MaintainanceComponent },
  { path: "feedback", component: MaintainanceComponent },
  { path: "employee-tracking", component: MaintainanceComponent },
  { path: "health-analysis", component: MaintainanceComponent },
  { path: "service", component: MaintainanceComponent },
  { path: "employees-temp", component: EmployeesTempComponent },
  { path: "employees-temp/:type", component: EmployeesTempComponent },
];
